ALTER TABLE `usagelimiter_v1_usage_records` ADD `cost` numeric;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `rate_amount` numeric;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `rate_currency` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `entitlement_snapshot_id` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `entitlement_version` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `entitlement_feature_type` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `entitlement_limit` integer;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `entitlement_overage_strategy` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `entitlement_effective_at` integer;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `entitlement_expires_at` integer;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_usage_records` ADD `entitlement_snapshot` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `usage` numeric;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `remaining` numeric;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `entitlement_snapshot_id` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `entitlement_version` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `entitlement_feature_type` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `entitlement_limit` integer;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `entitlement_overage_strategy` text;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `entitlement_effective_at` integer;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `entitlement_expires_at` integer;--> statement-breakpoint
ALTER TABLE `usagelimiter_v1_verifications` ADD `entitlement_snapshot` text;
