# name: CI

# on:
#   pull_request:
#   # TODO: change this
#     branches: ['main']
#   push:
#     branches: ['main']
#   merge_group:

# # You can leverage Vercel Remote Caching with Turbo to speed up your builds
# # @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
# env:
#   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#   TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
#   SKIP_ENV_VALIDATION: 1

# jobs:
#   build-lint:
#     env:
#       DATABASE_URL: file:./db.sqlite
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4
