name: CI

on:
  pull_request:
  # TODO: change this
    branches: ['main']
  push:
    branches: ['main']
  merge_group:

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  SKIP_ENV_VALIDATION: 1

jobs:
  build-lint:
    env:
      DATABASE_URL: file:./db.sqlite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: "dev"
          project-slug: "unprice-zq-xm"
          export-type: "file"
          file-output-path: ".env"
          secret-path: "/"

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.6.12
          run_install: false

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install --recursive

      - run: cp .env.example .env.local

      - name: Type-check
        run: pnpm turbo typecheck

      - name: Check formatting
        run: pnpm biome ci .

      - name: Check workspaces
        run: pnpm manypkg check

      - name: Run tests
        run: pnpm turbo test
