name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize]

env:
  SKIP_ENV_VALIDATION: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-lint:
    if: "!contains(github.head_ref, 'renovate/')"
    uses: ./.github/workflows/job_build.yaml
    with:
      pull_secrets: true
      project_slug: unprice-zq-xm
      env_slug: preview
    secrets:
      MACHINE_IDENTITY_CLIENT_ID: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
      MACHINE_IDENTITY_CLIENT_SECRET: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}

  deploy-preview-tinybird:
    if: "!contains(github.head_ref, 'renovate/')"
    runs-on: ubuntu-latest

    outputs:
      tb_branch_name: ${{ steps.set-output.outputs.branch_name }}
      tb_branch_token: ${{ steps.set-output.outputs.tb_branch_token }}

    permissions:
      pull-requests: write
      contents: read

    needs:
      - build-lint

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Infisical/secrets-action@v1.0.7
        name: Pull secrets from Infisical
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: "preview"
          project-slug: "unprice-zq-xm"
          secret-path: "/ci"
          recursive: true

      - uses: ./.github/actions/tinybirdci
        name: Deploy Preview Tinybird
        id: deploy-preview-tinybird
        with:
          tb_format: true
          tb_admin_token: ${{ env.TB_ADMIN_TOKEN }}
          tb_host: https://api.tinybird.co
          data_project_dir: internal/tinybird

      # TODO: https://nitratine.net/blog/post/how-to-pass-secrets-between-runners-in-github-actions/
      # https://github.com/marketplace/actions/secret-output
      - name: Set Outputs for Tinybird
        id: set-output
        shell: bash
        run: |
          echo "branch_name=${{ steps.deploy-preview-tinybird.outputs.branch_name }}" >> $GITHUB_OUTPUT
          echo "tb_branch_token=${{ steps.deploy-preview-tinybird.outputs.tb_branch_token }}" >> $GITHUB_OUTPUT

  deploy-preview-neon:
    if: "!contains(github.head_ref, 'renovate/')"
    runs-on: ubuntu-latest

    outputs:
      db_branch_name: ${{ steps.set-output.outputs.database_branch_name }}
      db_url: ${{ steps.set-output.outputs.database_url }}

    needs:
      - deploy-preview-tinybird

    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Infisical/secrets-action@v1.0.7
        name: Pull secrets from Infisical
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: "preview"
          project-slug: "unprice-zq-xm"
          secret-path: "/ci"
          recursive: true

      - uses: ./.github/actions/install
        with:
          ts: true

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Create Neon Branch
        id: create-branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          parent: main
          branch_name: preview/pr-${{ steps.branch-name.outputs.current_branch }}
          database: ${{ env.NEON_DATABASE_NAME }}
          api_key: ${{ env.NEON_API_KEY }}
          username: ${{ env.NEON_DATABASE_USERNAME }}

      - name: Run Migrations
        working-directory: internal/db
        run: |
          pnpm generate
          pnpm migrate:custom
        env:
          VERCEL_ENV: preview
          NODE_ENV: development
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}

      - name: commit migrations
        working-directory: internal/db
        run: |
          if [ -n "$(git status --porcelain ./)" ]; then
            echo "Changes detected in db folder, committing..."
            git config --global user.email "unprice-bot@unprice.com"
            git config --global user.name "Unprice Bot"
            git add .
            git commit -m "Migrations for preview"
            git push --set-upstream origin ${{ steps.branch-name.outputs.current_branch }}
          else
            echo "No changes detected in db folder, skipping commit"
          fi

      - name: Schema Diff
        uses: neondatabase/schema-diff-action@v1
        with:
          project_id: ${{ env.NEON_PROJECT_ID }}
          base_branch: main
          compare_branch: preview/pr-${{ steps.branch-name.outputs.current_branch }}
          username: ${{ env.NEON_DATABASE_USERNAME }}
          database: ${{ env.NEON_DATABASE_NAME }}
          api_key: ${{ env.NEON_API_KEY }}

      - name: Set Outputs for Neon
        id: set-output
        shell: bash
        run: |
          echo "database_branch_name=preview/pr-${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_OUTPUT
          echo "database_url=${{ steps.create-branch.outputs.db_url_with_pooler }}" >> $GITHUB_OUTPUT


  deploy-preview-vercel:
    if: "!contains(github.head_ref, 'renovate/')"
    runs-on: ubuntu-latest

    needs:
      - deploy-preview-neon
      - deploy-preview-tinybird

    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: Infisical/secrets-action@v1.0.7
        name: Pull secrets from Infisical
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: "preview"
          project-slug: "unprice-zq-xm"
          export-type: "file"
          file-output-path: "/.env"
          secret-path: "/"
          recursive: true

      - uses: ./.github/actions/install
        with:
          ts: true
          python: true

      - uses: cardinalby/export-env-action@v2
        with:
          envFile: '.env'
          export: true
          # export everything except DATABASE_URL and TINYBIRD_TOKEN using regex
          filter: ^(?!DATABASE_URL$|TINYBIRD_TOKEN$).*$
          mask: true

      - name: Check for changes
        id: turbo-ignore
        continue-on-error: true
        run: npx turbo-ignore -d apps/auth-proxy

      - uses: amondnet/vercel-action@v25.2.0 #deploy
        name: Deploy Unprice auth to Vercel
        id: deploy-auth
        # if turbo-ignore fails,that means there are no changes in the auth-proxy folder
        if: steps.turbo-ignore.outcome == 'failure'
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ env.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ env.VERCEL_PROJECT_AUTH_UNPRICE_ID }} #Required
          # always prod because the auth proxy link has to be stable
          vercel-args: '--prod --env VERCEL_ENV=production --env NODE_ENV=production --build-env NODE_ENV=production'
          working-directory: ./

      # deploy preview unprice to vercel
      - uses: amondnet/vercel-action@v25.2.0 #deploy
        name: Deploy Preview Unprice to Vercel
        id: deploy-unprice
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ env.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ env.VERCEL_PROJECT_UNPRICE_ID}} #Required
          working-directory: ./
          vercel-args: '--env NODE_ENV=production --env DATABASE_URL=${{ needs.deploy-preview-neon.outputs.db_url }} --env TINYBIRD_TOKEN=${{ needs.deploy-preview-tinybird.outputs.tb_branch_token }} --env NEXT_PUBLIC_APP_DOMAIN=pr-${{ github.event.number }}-unprice.vercel.app --env NEXT_PUBLIC_VERCEL_ENV=preview --build-env NODE_ENV=production --build-env DATABASE_URL=${{ needs.deploy-preview-neon.outputs.db_url }} --build-env TINYBIRD_TOKEN=${{ needs.deploy-preview-tinybird.outputs.tb_branch_token }} --build-env NEXT_PUBLIC_APP_DOMAIN=pr-${{ github.event.number }}-unprice.vercel.app --build-env NEXT_PUBLIC_VERCEL_ENV=preview'
          alias-domains: |
            pr-${{ github.event.number }}-unprice.vercel.app
            app-pr-${{ github.event.number }}-unprice.vercel.app
            api-pr-${{ github.event.number }}-unprice.vercel.app

      - name: Delete Secret
        if: always()
        run: |
          rm -rf .env || true
          rm -rf .tinyenv || true