name: Deploy API Staging
on:
  workflow_call:
    secrets:
      PASSWORD_ENCRYPT:
        required: true
      DATABASE_URL_ENCRYPTED:
        required: true
      MACHINE_IDENTITY_CLIENT_ID:
        required: true
      MACHINE_IDENTITY_CLIENT_SECRET:
        required: true


env:
  SKIP_ENV_VALIDATION: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install
        with:
          ts: true

      - uses: cloudposse/github-action-secret-outputs@main
        id: db-url
        with:
          ## PASSWORD is a gpg passphrase stored in Github Secrets.
          secret: ${{ secrets.PASSWORD_ENCRYPT }}
          op: decode
          in: ${{ secrets.DATABASE_URL_ENCRYPTED }}

      - uses: Infisical/secrets-action@v1.0.7
        name: Pull secrets from Infisical
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: "preview"
          project-slug: "unprice-zq-xm"
          secret-path: "/"
          recursive: true

      - name: Build
        run: pnpm turbo run build --filter='./apps/api'

      - name: Version
        run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Install Wrangler
        shell: bash
        run: |
          npm i -g wrangler@4.3.0
          wrangler --version

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.3.0"
          environment: "preview"
          packageManager: "pnpm"
          workingDirectory: "apps/api"
          # Pass secrets to Worker
          secrets: |
            CLOUDFLARE_API_TOKEN
            TINYBIRD_TOKEN
            TINYBIRD_URL
            AUTH_SECRET
            COOKIE_ENCRYPTION_KEY
            CLOUDFLARE_ZONE_ID
            DATABASE_URL
            DATABASE_READ1_URL
            DATABASE_READ2_URL
            ENCRYPTION_KEY
            BASELIME_APIKEY
          vars: |
            VERSION
            NODE_ENV
            VERCEL_ENV
            EMIT_METRICS_LOGS
            DRIZZLE_LOG
            VERCEL_ENV
        env:
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ env.CLOUDFLARE_ZONE_ID }}
          TINYBIRD_TOKEN: ${{ env.TINYBIRD_TOKEN }}
          TINYBIRD_URL: ${{ env.TINYBIRD_URL }}
          COOKIE_ENCRYPTION_KEY: ${{ env.COOKIE_ENCRYPTION_KEY }}
          AUTH_SECRET: ${{ env.AUTH_SECRET }}
          # we are passing the preview database url to the deploy action
          DATABASE_URL: ${{ steps.db-url.outputs.out }}
          EMIT_METRICS_LOGS: ${{ env.EMIT_METRICS_LOGS }}
          BASELIME_APIKEY: ${{ env.BASELIME_APIKEY }}
          VERCEL_ENV: ${{ env.VERCEL_ENV }}
          VERSION: ${{ env.VERSION }}
          NODE_ENV: ${{ env.NODE_ENV }}
          DRIZZLE_LOG: ${{ env.DRIZZLE_LOG }}
          VERCEL_ENV: ${{ env.VERCEL_ENV }}
          ENCRYPTION_KEY: ${{ env.ENCRYPTION_KEY }}
