name: Build

on:
  workflow_call:
    inputs:
      pull_secrets:
        type: boolean
        default: true
        description: Whether to pull secrets from Infisical
      project_slug:
        type: string
        description: The slug of the project
      env_slug:
        type: string
        description: The slug of the environment
    secrets:
      MACHINE_IDENTITY_CLIENT_ID:
        required: true
      MACHINE_IDENTITY_CLIENT_SECRET:
        required: true


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/install
        name: Install dependencies
        with:
          ts: "true"
          python: "false"

      - name: Type-check
        run: pnpm typecheck
        env:
          NODE_ENV: test

      - name: Check formatting
        run: pnpm biome ci .

      - name: Check workspaces
        run: pnpm manypkg check

      - name: Run tests
        run: pnpm test
        env:
          # fake database url
          DATABASE_URL: postgresql://postgresql:postgresql@localhost:5432/unprice
          NODE_ENV: test




