name: Tinybird - CD Workflow

on:
  workflow_call:

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: internal/tinybird
    steps:
      - uses: actions/checkout@v4

      - name: should deploy only if changes in tinybird folder
        run: |
          # Get the base SHA for comparison
          BASE_SHA=$(git rev-parse origin/main)

          if git diff --name-only $BASE_SHA HEAD | grep -q "internal/tinybird"; then
            echo "Changes detected in the tinybird folder"
          else
            echo "No changes in the tinybird folder"
            exit 0
          fi

      - name: Install Tinybird CLI
        run: curl -LsSf https://api.tinybird.co/static/install.sh | sh

      - uses: Infisical/secrets-action@v1.0.7
        name: Pull secrets from Infisical
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: "prod"
          project-slug: "unprice-zq-xm"
          secret-path: "/ci"
          recursive: true

      - name: Authenticate
        run: tb auth --host https://api.europe-west2.gcp.tinybird.co  --token ${{ env.TB_ADMIN_TOKEN }}

      - name: Deploy project
        run: tb --cloud deploy