name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/install/action.yaml

      - name: Type-check
        run: pnpm turbo typecheck

      - name: Check formatting
        run: pnpm biome ci .

      - name: Check workspaces
        run: pnpm manypkg check

      - name: Run tests
        run: pnpm turbo test





