name: Build
on:
  workflow_call:
  secrets:
    MACHINE_IDENTITY_CLIENT_ID:
      required: true
    MACHINE_IDENTITY_CLIENT_SECRET:
      required: true
    PROJECT_SLUG:
      required: true
    ENV_SLUG:
      required: true


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: ${{ env.ENV_SLUG }}
          project-slug: ${{ env.PROJECT_SLUG }}
          export-type: "file"
          file-output-path: ".env"
          secret-path: "/"

      - uses: ./.github/actions/install

      - name: Type-check
        run: pnpm turbo typecheck

      - name: Check formatting
        run: pnpm biome ci .

      - name: Check workspaces
        run: pnpm manypkg check

      - name: Run tests
        run: pnpm turbo test





