name: Tinybird - CD Workflow

on:
  workflow_call:

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: internal/tinybird
    steps:
      - uses: actions/checkout@v4
      - name: Install Tinybird CLI
        run: curl -LsSf https://api.tinybird.co/static/install.sh | sh
      - name: Authenticate
        run: tb auth --host https://api.europe-west2.gcp.tinybird.co --token ${{ secrets.TB_ADMIN_TOKEN }}
      - name: Deploy project
        run: tb --cloud deploy