name: Tinybird - CD Workflow

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string

jobs:
  cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: internal/tinybird
    steps:
      - uses: actions/checkout@v4

      - name: Install Tinybird CLI
        if: steps.should-deploy.outputs.skip != '1'
        run: curl https://tinybird.co | sh

      - uses: Infisical/secrets-action@v1.0.7
        name: Pull secrets from Infisical
        if: steps.should-deploy.outputs.skip != '1'
        with:
          client-id: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
          client-secret: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
          env-slug: ${{ inputs.env }}
          project-slug: "unprice-zq-xm"
          secret-path: "/ci"
          recursive: true

      - name: Authenticate
        if: steps.should-deploy.outputs.skip != '1'
        run: tb auth --host https://api.europe-west2.gcp.tinybird.co  --token ${{ env.TB_ADMIN_TOKEN }}

      - name: Verify deployment
        if: steps.should-deploy.outputs.skip != '1'
        run: tb --cloud deploy --check

      - name: Deploy to cloud ${{ inputs.env }}
        if: steps.should-deploy.outputs.skip != '1'
        run: tb --cloud deploy