name: Test Renovate

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - "renovate/**"

env:
  SKIP_ENV_VALIDATION: 1

jobs:
  build-lint:
    uses: ./.github/workflows/job_build.yaml
    with:
      pull_secrets: true
      project_slug: unprice-zq-xm
      env_slug: preview
    secrets:
      MACHINE_IDENTITY_CLIENT_ID: ${{ secrets.MACHINE_IDENTITY_CLIENT_ID }}
      MACHINE_IDENTITY_CLIENT_SECRET: ${{ secrets.MACHINE_IDENTITY_CLIENT_SECRET }}
