name: Test Renovate

on:
  pull_request:
    types: [opened, synchronize]

env:
  SKIP_ENV_VALIDATION: 1

jobs:
  build-lint:
    uses: ./.github/workflows/job_build.yaml
    if: "contains(github.head_ref, 'renovate/')"
